name: CatchTheBoat
version: ${project.version}
main: com.github.militaermilitz.CatchTheBoat
api-version: 1.15
authors: [ MilitaerMilitz ]
description: This Plugin enables Battleship (aka. Catch the boat) in Minecraft.
depend:
  - StructureBlockLib

commands:
  battleship:
    description: Create or remove a game.
    usage: Right usage -> /battleship <create/remove> <if create -> big/small>
    permission: catchTheBoat.battleship
    permission-message: You don't have the permission to do that.
